# Generated by Django 4.1.7 on 2023-02-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pilotageSchool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='adress',
            new_name='address',
        ),
    ]
