# Generated by Django 4.1.7 on 2023-03-09 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotageSchool', '0002_remove_reservation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
