# Generated by Django 4.1.7 on 2023-03-09 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilotageSchool', '0003_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
